[package]
name = "just_a_calculator"
author = ["Albert Julian Tannady <albertjulian97@gmail.com>"]
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
